### ISSUE TITLE
My video titles are black 

### ISSUE THREAD

**Issue by simdog765** [PoomSmart/YTABConfig#115]
Hey there, I copied your setting to fix the crashing issue
But now all my titles are black, and I do not know how to fix it

I’m hoping to have all the standard features that uYou came with

**Comment by PoomSmart** [comment]
Closing for not related to YTABConfig.

**Comment by simdog765** [comment]
How can you say it’s not related when I got the settings from your page. Can you please tell me how to fix my issue Sent from my iPhoneOn Apr 28, 2024, at 4:10 AM, Thatchapon Unprasert ***@***.***> wrote:﻿
Closing for not related to YTABConfig.

**Comment by PoomSmart** [comment]
Nope, YTABConfig's sole responsibility is to provide you a way to manage the flags, not to deal with the effects from toggling the flags. This is where Discussions tab comes in handy.
