### ISSUE TITLE
Copy to Clipboard broken again

### ISSUE THREAD

**Issue by bhackel** [PoomSmart/YTABConfig#116]
Hello

I noticed that Copy to Clipboard is not working on Youtube version 19.14.2 but is working on 19.06.2 with the latest commits from this repo. I will be able to find the specific version in a few hours. Here is the crash log:

[YouTube-2024-04-29-154435.json](https://github.com/PoomSmart/YTABConfig/files/15155684/YouTube-2024-04-29-154435.json)

**Comment by PoomSmart** [comment]
The latest version of YTABConfig already fixed this issue.

**Comment by bhackel** [comment]
Ah sorry about that, I must have installed the wrong IPA
