### ISSUE TITLE
Search doesn't show results

### ISSUE THREAD

**Issue by ErSpieltHD** [PoomSmart/YTABConfig#17]
When grouping settings the search doesn't find specific settings but only the group. Like if you search enableiosroundedsearch it doesn't find anything until you delete everything except enable. Then it only finds the group beginning with enable

**Comment by PoomSmart** [comment]
Do you have "Group settings by prefixes" enabled?

**Comment by PoomSmart** [comment]
That's expected and that's the current limitation of the search feature.
