### ISSUE TITLE
[Enhancement] Paste AB Flags

### ISSUE THREAD

**Issue by yodaluca23** [PoomSmart/YTABConfig#45]
There is currently the ability to "Copy" all your changed A/B flags, however, it is really tedious to import if you want to share it with someone, or use it as a backup. My idea is right below the "Copy" button, add a "Paste" button, it will give you a preview of the A/B flags that will be overwritten, and then you press either "Import/Override/Confirm" (Or something along those lines) or "Cancel/Abort".

**Comment by arichorn** [comment]
Also Yodaluca, it’s alright if this idea doesn’t make it. People can copy the modified A/B flags to the clipboard and search each Flag and enable each one, not the best workaround for “Pasting A/B Flags” but it is the only working and time consuming workaround.

**Comment by yodaluca23** [comment]
> Also Yodaluca, it’s alright if this idea doesn’t make it. People can copy the modified A/B flags to the clipboard and search each Flag and enable each one, not the best workaround for “Pasting A/B Flags” but it is the only working and time consuming workaround.

Yea, but for some reason the search bar only shows up when you have them ungrouped... LOL

**Comment by arichorn** [comment]
Oh I didn’t know it the search bar would show up ungrounded. Whoops 😅

**Comment by PoomSmart** [comment]
v1.6.0 adds an ability to import the settings, but it won't import a very large number of settings (thousands?) yet.

I'm not very sure if we want the tweak to import every single setting and bloat the app preference plist, because most of the time you benefit from only less than hundreds keys anyway.
