### ISSUE TITLE
Would you make the function customizable？"LongPressPlayerOverlay" 

### ISSUE THREAD

**Issue by dzxcvp** [PoomSmart/YTABConfig#62]
“YTColdConfig.enableLongPressPlayerOverlayToPlayWithDoubleSpeed“
is great! 
Especially when I’m watching long lecture videos, I always want to speed up those parts that are easy to understand. 
Yet x2 speed is still not fast enough for me sometimes. 
Can you make the speed option customizable? Or just add x2.5, x2.75, x3 as options?
The most convenient function would be like this: slide finger up or down when long pressing to adjust speed, + or - x0.25 when sliding a bit.

**Comment by PoomSmart** [comment]
Sounds like a good idea. The only uncertain thing is whether I have time and a will to do it. Guess we will see.
